server:
    host: "127.0.0.1"
    port: ":8080"
    timeout: 5s

repository:
    maxAttempts: 3
    username: "postgres"
    password: "12345"
    host: "127.0.0.1"
    port: "5438"
    database: "postgres"