version: '3.8'

services:
  app:
    image: shop
    container_name: shop-app
    depends_on:
      - postgresql
      - redis
    ports:
      - "127.0.0.1:8090:8090"
    networks:
      - ps

  postgresql:
    image: postgres:alpine
    container_name: ps-psql
    restart: always
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - ps

  redis:
    image: redis/redis-stack:latest
    container_name: rs-redis
    restart: always
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - ./data:/data
    networks:
      - ps

networks:
  ps: