server:
    host: "127.0.0.1" # Local: 127.0.0.1, Docker: 0.0.0.0
    port: ":8080"
    timeout: 5s

postgres:
    maxAttempts: 4
    delay: 10s
    username: "postgres"
    password: "12345"
    host: "127.0.0.1" # Local: 127.0.0.1, Docker: postgresql
    port: "5432" # Local: 5432, Docker: 5432
    database: "postgres"
    SSLMode: "disable"

redis:
    username: "reds"
    password: ""
    host: "127.0.0.1" # Local: 127.0.0.1, Docker: redis
    port: "6379"
    database: "0"

logger:
    logLevel: "debug"

auth:
    signingKey: "hs1dfjKhl0iLLLhfjH7"
    accessTokenTTL: 2h
    refreshTokenTTL: 4h