server:
    host: "127.0.0.1"
    port: ":8080"
    timeout: 5s

repository:
    maxAttempts: 3
    username: "postgres"
    password: "12345"
    host: "127.0.0.1" # Local: 127.0.0.1, Docker: postgresql
    port: "5438" # Local: 5438, Docker: 5432
    database: "postgres"
    SSLMode: "disable"

logger:
    logLevel: "debug"

auth:
    signingKey: "hs1dfjKhl0iLLLhfjH7"
    accessTokenTTL: 2h
    refreshTokenTTL: 4h